### ISSUE TITLE
Simplify. Spacing

### ISSUE THREAD

**Issue by kalverra** [hartfib/prj-rev-bwfs-tea-cozy#4]
https://github.com/hartfib/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L36-L59

Some unnecessary spacing here, keep it to one line, too much actually hurts readability. Only use spacing to separate large portions of code.

**Comment by hartfib** [comment]
Yes, I use a lot of space so I can see what I'm doing.  I will make sure I remember to get rid of all the space once I have completed a project
