### ISSUE TITLE
Simplify. CSS Organization

### ISSUE THREAD

**Issue by kalverra** [hartfib/prj-rev-bwfs-tea-cozy#5]
https://github.com/hartfib/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/css/stylesheet.css#L15-L18

Some small organizational changes can really help make your CSS much easier to read, check out this style guide. https://google.github.io/styleguide/htmlcssguide.html

**Comment by hartfib** [comment]
AWESOME!!!!!!  I have bookmarked this page.  Thank you!
