### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by kalverra** [hartfib/prj-rev-bwfs-tea-cozy#6]
**Grade**: Exceeds Expectations

**Summary**:
Well done here, your code is both functional and well organized, meeting our spec and easy to read. Both functionality and readability are about equally crucial in the programming world, and you seem to have paid sufficient attention to both, so well done. I have some organizational nitpicks that I've highlighted, check out the resources and see how you can make things just a bit cleaner.

For future projects, try throwing in your own little bits of style to dress up the site and personalize it. It's good to practice design along with functional code, so use these templates as opportunity to try some things. http://www.webdesign-inspiration.com/web-designs/style/modern

**Comment by hartfib** [comment]
Hi 
Thank you so much for the review.  Yes, I do tend to use A LOT of space in my code especially in my .net code.  I've had many people actually laugh at me and it's become a running joke.  I'm trying.  Thank you for the organizational tips!!!!!
